export const hackathonInfo = [
  {
    hackId: 1,
    hackName: "해커퉁1",
    startDate: "2024-12-1",
    endDate: "2024-12-31",
    link: "",
    memNumber: 4,
    maxMemNumber: 4,
    description: "오늘의 날씨를 알려주자!!!! ",
    video: "https://tv.naver.com/v/66037262",
    pictures: "",
    coverImage: "",
    logo: "",
    ownerId: "happytree12",
    ownerEmail: "tylove@naver.com",
    participant: [
      "admin1",
      "happytree12",
      "backendDevel1!"
    ],
    part: "프론트엔드"
  },
  {
    hackId: 2,
    hackName: "해커톤2",
    startDate: "2024-11-1",
    endDate: "2024-12-31",
    link: "",
    memNumber: 20,
    maxMemNumber: 20,
    description: "설명입니다",
    video: "",
    pictures: "",
    coverImage: "",
    logo: "",
    ownerId: "backendDevel1!",
    ownerEmail: "sylove@naver.com",
    participant: [
      "happytree12"
    ],
    part: "백엔드"
  },
  {
        hackId: 3,
        hackName: "",
        startDate: "2024-12-11",
        endDate: "2024-12-27",
        link: "dkssu",
        maxMemNumber: 20,
        description: "안녕",
        video: "",
        pictures: [],
        coverImage: "",
        logo: "",
        part: "안녕",
        ownerId: "te4939",
        ownerEmail: "tylove@naver.com",
        participant: [],
  },
  {
    hackId: 3,
    hackName: "",
    startDate: "2024-12-11",
    endDate: "2024-12-27",
    link: "dkssu",
    maxMemNumber: 30,
    description: "안녕",
    video: "",
    pictures: [],
    coverImage: "",
    logo: "",
    part: "ㅇ",
    ownerId: "te4939",
    ownerEmail: "tylove@naver.com",
    participant: [],
},
{
        hackId: 4,
        hackName: "안녕",
        startDate: "2024-12-16",
        endDate: "2024-12-25",
        link: "ff",
        maxMemNumber: 2,
        description: "안녕",
        video: "",
        pictures: ["uploads/dugi.jpg","uploads/sssss.jpg"],
        coverImage: "uploads/kkkkk.jpg",
        logo: "",
        part: "디자인",
        ownerId: "happytree12",
        ownerEmail: "tylove@naver.com",
        participant: [],
    },
{
        hackId: 5,
        hackName: "ss",
        startDate: "2024-12-12",
        endDate: "2024-12-27",
        link: "ss",
        maxMemNumber: 3,
        description: "ss",
        video: "",
        pictures: ["uploads/dgaier.jpg"],
        coverImage: "uploads/kkkkk.jpg",
        logo: "uploads/dugi.jpg",
        part: "ssss",
        ownerId: "happytree12",
        ownerEmail: "tylove@naver.com",
        participant: [],
    },
];