export const hackathonInfo = [
  {
    hackId: 1,
    hackName: "해커퉁1",
    startDate: "2024-12-1",
    endDate: "2024-12-31",
    link: "",
    memNumber: 4,
    maxMemNumber: 4,
    description: "오늘의 날씨를 알려주자!!!! ",
    video: "",
    pictures: "",
    coverImage: "",
    logo: "",
    ownerId: "happytree12",
    ownerEmail: "tylove@naver.com",
    participant: [
      "admin1",
      "happytree12",
      "backendDevel1!"
    ],
    part: "프론트"
  },
  {
    hackId: 2,
    hackName: "해커톤2",
    startDate: "2024-11-1",
    endDate: "2024-12-31",
    link: "",
    memNumber: 20,
    maxMemNumber: 20,
    description: "설명입니다",
    video: "",
    pictures: "",
    coverImage: "",
    logo: "",
    ownerId: "backendDevel1!",
    ownerEmail: "sylove@naver.com",
    participant: [
      "happytree12"
    ],
    part: "프론트"
  },
  {
    hackId: 6,
    hackName: "ㅇㅇ",
    startDate: "2024-12-22",
    endDate: "2024-12-25",
    link: "ddd",
    memNumber: 2,
    maxMemNumber: 20,
    description: "ㄴ",
    video: "",
    pictures: "",
    coverImage: "",
    logo: "",
    part: "fdbv c",
    ownerId: "5",
    ownerEmail: "example@example.com",
    participant: [
      "happytree12",
      "backendDevel1!"
    ]
  },
  {
    hackId: 7,
    hackName: "sfiovb",
    startDate: "2024-12-22",
    endDate: "2024-12-25",
    link: "ddd",
    memNumber: 0,
    maxMemNumber: 20,
    description: "ㄴ",
    video: "",
    pictures: "",
    coverImage: "",
    logo: "",
    part: "fdbv c",
    ownerId: "5",
    ownerEmail: "example@example.com",
    participant: [
      "happytree12"
    ]
  },
  {
    hackId: 8,
    hackName: "dd",
    startDate: "2024-12-09",
    endDate: "2024-12-12",
    link: "dd",
    maxMemNumber: 2,
    description: "dd",
    video: "",
    pictures: "",
    coverImage: "",
    logo: "",
    part: "dd",
    ownerId: "5",
    ownerEmail: "example@example.com",
    participant: [
      "dd",
      "dd"
    ]
  },
  {
    hackId: 9,
    hackName: "안녕",
    startDate: "2024-12-07",
    endDate: "2024-12-13",
    link: "",
    maxMemNumber: 23,
    description: "ㅇㅎㅁ",
    video: "",
    pictures: "",
    coverImage: "",
    logo: "",
    part: "안녕",
    ownerId: "happytree12",
    ownerEmail: "tylove@naver.com",
    participant: []
  },
  {
    hackId: 10,
    hackName: "ss",
    startDate: "2024-12-16",
    endDate: "2024-12-20",
    link: "",
    maxMemNumber: 2,
    description: "ss",
    video: "",
    pictures: "",
    coverImage: "",
    logo: "",
    part: "ss",
    ownerId: "happytree12",
    ownerEmail: "tylove@naver.com",
    participant: []
  }, 
  {
    hackId: 11,
    hackName: "d",
    startDate: "2024-12-23",
    endDate: "2024-12-25",
    link: "dd",
    maxMemNumber: 333,
    description: "dd",
    video: "",
    pictures: "",
    coverImage: "uploads/cccc.jpg",
    logo: "uploads/ddddd.jpg",
    part: "dddd",
    ownerId: "happytree12",
    ownerEmail: "tylove@naver.com",
    participant: [],
}
  
,    {
        hackId: 12,
        hackName: "d",
        startDate: "2024-12-23",
        endDate: "2024-12-28",
        link: "dd",
        maxMemNumber: 3,
        description: "ddddd",
        video: "",
        pictures: "[]",
        coverImage: "uploads/sssss.jpg",
        logo: "uploads/ddddd.jpg",
        part: "dddd",
        ownerId: "happytree12",
        ownerEmail: "tylove@naver.com",
        participant: [],
    }
];