export const hackathonInfo = [
  {
    hackId: 1,
    hackName: "해커퉁1",
    startDate: "2024-12-1",
    endDate: "2024-12-31",
    link: "",
    memNumber: 4,
    maxMemNumber: 4,
    description: "오늘의 날씨를 알려주자!!!! ",
    video: "",
    pictures: "",
    coverImage: "",
    logo: "",
    ownerId: "happytree12",
    ownerEmail: "tylove@naver.com",
    participant: [
      "admin1",
      "happytree12",
      "backendDevel1!"
    ],
    part: "프론트"
  },
  {
    hackId: 2,
    hackName: "해커톤2",
    startDate: "2024-11-1",
    endDate: "2024-12-31",
    link: "",
    memNumber: 20,
    maxMemNumber: 20,
    description: "설명입니다",
    video: "",
    pictures: "",
    coverImage: "",
    logo: "",
    ownerId: "backendDevel1!",
    ownerEmail: "sylove@naver.com",
    participant: [],
    part: "프론트"
  },
  {
    hackId: 3,
    hackName: "ㅇㅎㅎ",
    startDate: "2024-11-28",
    endDate: "2024-11-29",
    link: "dfgrg",
    memNumber: 2,
    description: "fag",
    video: "",
    pictures: "",
    coverImage: "",
    logo: "",
    ownerId: "happytree12",
    ownerEmail: "tylove@naver.com",
    part: "프론트"
  },
  {
    hackId: 4,
    hackName: "DDD",
    startDate: "2024-11-13",
    endDate: "2024-11-26",
    link: "DGF",
    memNumber: 2,
    description: "DD",
    video: "",
    pictures: "",
    coverImage: "",
    logo: "",
    part: "백인데요",
    ownerId: "happytree12",
    ownerEmail: "tylove@naver.com"
  }
,    {
        hackId: 5,
        hackName: "ㅇㅇ",
        startDate: "2024-12-02",
        endDate: "2024-12-02",
        link: "link",
        memNumber: 5,
        description: "tjfaud",
        video: "",
        pictures: "",
        coverImage: "",
        logo: "",
        part: "backend",
        ownerId: "backendDevel1!",
        ownerEmail: "sylove@naver.com",
    }
];