// 이 정보는 모든 개발자 유저가 템플릿 양식 속에 자신의 정보를 담은 모든 포트폴리오이다.
export const portfolioInfo = [
  {
    portfolioId: 1,
    portfolioName: "훔훔..",
    ownerId: "admin1",
    ownerEmail: "nabinabi1110@naver.com",
    projects: [1, 2],
    usedLanguage: "Java",
    share: true,
  },
  {
    portfolioId: 2,
    portfolioName: "왜 안돼..",
    ownerId: "admin1",
    ownerEmail: "nabinabi1110@naver.com",
    projects: [1],
    usedLanguage: "Phython",
    share: false,
  },
{
    portfolioId: 3,
    portfolioName: "과연",
    ownerName: "김예은",
    ownerId: "admin1",
    ownerEmail: "nabinabi1110@naver.com",
    projects: [1,2],
    usedLanguage: "쳇쳇",
    frontend: "Node.js",
    backend: "Firebase",
    share: false
  },
{
    portfolioId: 4,
    portfolioName: "asdffs",
    ownerName: "김태연",
    ownerId: "happytree12",
    ownerEmail: "tylove@naver.com",
    projects: [3],
    usedLanguage: "JavaScriptd",
    frontend: "dfsf",
    backend: "sdf",
    share: false
  },
{
    portfolioId: 5,
    portfolioName: "asas",
    ownerName: "김태연",
    ownerId: "happytree12",
    ownerEmail: "tylove@naver.com",
    projects: [3,4,10],
    usedLanguage: "asa",
    frontend: "asas",
    backend: "asas",
    share: false
  },
{
    portfolioId: 6,
    portfolioName: "asdfsf",
    ownerName: "김태연",
    ownerId: "happytree12",
    ownerEmail: "tylove@naver.com",
    projects: [3,10,11],
    usedLanguage: "sfsdf",
    frontend: "sdfsdf",
    backend: "asdfs",
    share: false
  },
{
    portfolioId: 7,
    portfolioName: "ㅁㅇㄹ",
    ownerName: "김태연",
    ownerId: "happytree12",
    ownerEmail: "tylove@naver.com",
    projects: [3,13,10],
    usedLanguage: "ㄴㅇㄹㄴㄹ",
    frontend: "ㄴㅇㄹㅇㄴ",
    backend: "ㄴㅇㄹㅇㄹ",
    share: false
  },
{
    portfolioId: 8,
    portfolioName: "ㅇㅇ",
    ownerName: "김태연",
    ownerId: "happytree12",
    ownerEmail: "tylove@naver.com",
    projects: [11,4],
    usedLanguage: "ㅇㅇ",
    frontend: "ㅇㅇㅇㅇ",
    backend: "ㅇㅇ",
    share: false
  },
];