export const projectInfo = [
  {
    projectId: 1,
    ownerId: "admin1",
    ownerName: "김예은",
    ownerNickname: "옝",
    ownerEmail: "nabinabi1110@naver.com",
    usedTemplate: 1,
    projectTitle: "마라탕후루",
    description: "현재 제가 만든 모든 프로그램을 정리하였습니다.",
    startDate: "2024.11.11",
    endDate: "2024.11.18",
    solving: "이러이러한 곳에 사용할 수 있습니다.",
    challenge: "이러이러한 문제를 해결했습니다.",
    share: false,
    usedLanguage: "Java",
    category: "백엔드",
    hits: 0,
    contacts: []
  },
  {
    projectId: 2,
    ownerId: "admin1",
    ownerName: "김예은",
    ownerNickname: "옝",
    ownerEmail: "nabinabi1110@naver.com",
    usedTemplate: 1,
    projectTitle: "마루",
    description: "현재 제가 만든 모든 프로그램을 정리하였습니다.",
    startDate: "2024.11.12",
    endDate: "2024.11.22",
    solving: "이러이러한 곳에 사용할 수 있습니다.",
    challenge: "이러이러한 문제를 해결했습니다.",
    share: true,
    usedLanguage: "Java",
    category: "백엔드",
    hits: 3,
    contacts: [
      "admin1"
    ]
  },
  {
    projectId: 3,
    ownerId: "admin2",
    ownerName: "김태연",
    ownerNickname: "탱구리",
    ownerEmail: "tylove@naver.com",
    usedTemplate: 3,
    projectTitle: "탱의 포폴1",
    description: "현재 제가 만든 모든 프로그램을 정리하였습니다.",
    startDate: "2024.11.01",
    endDate: "2024.11.30",
    solving: "이러이러한 곳에 사용할 수 있습니다.",
    challenge: "이러이러한 문제를 해결했습니다.",
    share: true,
    usedLanguage: "JavaScript",
    category: "프론트엔드",
    hits: 16,
    contacts: [
      "admin1"
    ]
  },
  {
    projectId: 4,
    ownerId: "admin2",
    ownerName: "김태연",
    ownerNickname: "탱구리",
    ownerEmail: "tylove@naver.com",
    usedTemplate: 2,
    projectTitle: "탱의 포폴2",
    description: "현재 제가 만든 모든 프로그램을 정리하였습니다.",
    startDate: "2024.10.01",
    endDate: "2024.11.30",
    solving: "이러이러한 곳에 사용할 수 있습니다.",
    challenge: "이러이러한 문제를 해결했습니다.",
    share: true,
    usedLanguage: "JavaScript",
    category: "프론트엔드",
    hits: 1,
    contacts: []
  },
  {
    projectId: 5,
    ownerId: "admin3",
    ownerName: "조수연",
    ownerNickname: "수여니",
    ownerEmail: "sylove@naver.com",
    usedTemplate: 2,
    projectTitle: "수여니의 포폴1",
    description: "현재 제가 만든 모든 프로그램을 정리하였습니다.",
    startDate: "2024.09.01",
    endDate: "2024.10.30",
    solving: "이러이러한 곳에 사용할 수 있습니다.",
    challenge: "이러이러한 문제를 해결했습니다.",
    share: true,
    usedLanguage: "Phython",
    category: "백엔드",
    hits: 2,
    contacts: []
  },
  {
    projectId: 6,
    ownerId: "admin3",
    ownerName: "조수연",
    ownerNickname: "수여니",
    ownerEmail: "sylove@naver.com",
    usedTemplate: 1,
    projectTitle: "수여니의 포폴2",
    description: "현재 제가 만든 모든 프로그램을 정리하였습니다.",
    startDate: "2024.07.01",
    endDate: "2024.08.30",
    solving: "이러이러한 곳에 사용할 수 있습니다.",
    challenge: "이러이러한 문제를 해결했습니다.",
    share: true,
    usedLanguage: "Java",
    category: "백엔드",
    hits: 0,
    contacts: []
  },
  {
    projectId: 7,
    ownerId: "admin4",
    ownerName: "최현혜",
    ownerNickname: "현혜씽",
    ownerEmail: "hhlove@naver.com",
    usedTemplate: 4,
    projectTitle: "현혜씽의 포폴1",
    description: "현재 제가 만든 모든 프로그램을 정리하였습니다.",
    startDate: "2024.08.01",
    endDate: "2024.08.30",
    solving: "이러이러한 곳에 사용할 수 있습니다.",
    challenge: "이러이러한 문제를 해결했습니다.",
    share: true,
    usedLanguage: "Java",
    category: "백엔드",
    hits: 27,
    contacts: [
      "admin1"
    ]
  },
  {
    projectId: 8,
    ownerId: "admin4",
    ownerName: "최현혜",
    ownerNickname: "현혜씽",
    ownerEmail: "hhlove@naver.com",
    usedTemplate: 2,
    projectTitle: "현혜씽의 포폴2",
    description: "현재 제가 만든 모든 프로그램을 정리하였습니다.",
    startDate: "2024.11.01",
    endDate: "2024.11.30",
    solving: "이러이러한 곳에 사용할 수 있습니다.",
    challenge: "이러이러한 문제를 해결했습니다.",
    share: true,
    usedLanguage: "Java",
    category: "백엔드",
    hits: 10,
    contacts: [
      "admin1"
    ]
  }
,
  {
      projectId: 9,
      projectTitle: "d", 
      projectOwnerName: "최현혜",
      description: "d",
      startDate: "Fri Nov 22 2024 00:00:00 GMT+0900 (한국 표준시)", 
      endDate: "Wed Nov 27 2024 00:00:00 GMT+0900 (한국 표준시)", 
      category: "d", 
      usedLanguage: "d", 
      projectLink: "d",
      solving: "d", 
      challenge: "d",
      video: "비디오 없음.",
      coverImage: "없음.", 
      images: [], 
      logo: "없음.", 
     
      share: false
  }
];