export const userInfo = [
  {
    id: "admin1",
    pageId: 1,
    password: "close22@@",
    name: "김예은",
    phoneNumber: "010-2222-2222",
    birthday: "1990-01-01",
    recruiter: true,
    email: "nabinabi1110@naver.com",
    nickname: "옝",
    link: "",
    career: "있음",
    education: "학사",
    contacts: [],
  },
  {
    id: "happytree12",
    pageId: 2,
    password: "close12@@",
    name: "김태연",
    phoneNumber: "010-1234-5678",
    birthday: "1990-01-01",
    recruiter: false,
    email: "tylove@naver.com",
    nickname: "탱구리",
    link: "",
    career: "없음",
    education: "학사",
    contacts: [],
  },
  {
    id: "backendDevel1!",
    pageId: 3,
    password: "close12@@",
    name: "조수연",
    phoneNumber: "010-1234-5678",
    birthday: "1990-01-01",
    recruiter: false,
    email: "sylove@naver.com",
    nickname: "이쁜이",
    link: "",
    career: "없음",
    education: "석사",
    contacts: [],
  },
  {
    id: "admin4",
    pageId: 4,
    password: "oneofthefolio12!@",
    name: "최현혜",
    phoneNumber: "010-1234-5678",
    birthday: "1990-01-01",
    recruiter: false,
    email: "hhlove@naver.com",
    nickname: "현혜씽",
    link: "",
    career: "있음",
    education: "박사",
  },
  {
    id: "5",
    pageId: 5,
    password: "close12@@",
    name: "홍길동",
    phoneNumber: "010-1234-5678",
    birthday: "1990-01-01",
    recruiter: false,
    email: "example@example.com",
    nickname: "흰둥이",
    link: "",
    career: "있음",
    education: "석사",
  },
  {
    id: "6",
    pageId: 6,
    password: "close12@@",
    name: "홍길동",
    phoneNumber: "010-1234-5678",
    birthday: "1990-01-01",
    recruiter: false,
    email: "example@example.com",
    nickname: "honghong",
    link: "",
    career: "없음",
    education: "박사",
  },
  {
    id: "7",
    pageId: 7,
    password: "close12@@",
    name: "홍길동",
    phoneNumber: "010-1234-5678",
    birthday: "1990-01-01",
    recruiter: false,
    email: "example@example.com",
    nickname: "길동이",
    link: "",
    career: "있음",
    education: "석사",
  },
  {
    id: "user100000",
    pageId: 8,
    password: "close122222@@",
    name: "프레",
    phoneNumber: "010-2222-3333",
    birthday: "2024-11-06",
    recruiter: false,
    email: "",
    nickname: "",
    link: "",
    career: "없음",
    education: "",
  },
  {
    id: "removefromfile",
    pageId: 9,
    password: "removefromfile1!@",
    name: "삭제오류잡자",
    phoneNumber: "010-4343-4343",
    birthday: "2024-10-31",
    recruiter: false,
    email: "",
    nickname: "",
    link: "",
    career: "없음",
    education: "",
  },
  {
    id: "cleansaveinfo",
    pageId: 10,
    password: "cleansaveinfo12!@",
    name: "깔끔하게",
    phoneNumber: "010-2222-3344",
    birthday: "2024-11-04",
    recruiter: false,
    email: "",
    nickname: "",
    link: "",
    career: "없음",
    education: "",
  },
  {
    id: "world443322",
    pageId: 11,
    password: "close122222@@",
    name: "제발요",
    phoneNumber: "010-3343-4343",
    birthday: "2024-11-04",
    recruiter: false,
    email: "",
    nickname: "",
    link: "",
    career: "없음",
    education: "",
  },
  {
    id: "okaykimofyou",
    pageId: 12,
    password: "close122222@@",
    name: "강경",
    phoneNumber: "010-4343-4444",
    birthday: "2024-05-22",
    recruiter: false,
    email: "",
    nickname: "",
    link: "",
    career: "없음",
    education: "",
  },
  {
    id: "my._.movie_lover",
    pageId: 13,
    password: "cinefilechoi1!@",
    name: "영화",
    phoneNumber: "010-1112-2233",
    birthday: "2024-11-07",
    recruiter: false,
    email: "",
    nickname: "",
    link: "",
    career: "없음",
    education: "",
  },
  {
    id: "whyisntwork",
    pageId: 14,
    password: "whyisntwork12!@",
    name: "외않되",
    phoneNumber: "010-4343-4300",
    birthday: "2024-11-18",
    recruiter: false,
    email: "",
    nickname: "",
    link: "",
    career: "없음",
    education: "",
  },
  {
    id: "feelingsogood",
    pageId: 15,
    password: "close122222@@",
    name: "도파민터짐",
    phoneNumber: "010-3423-4324",
    birthday: "2024-11-04",
    recruiter: false,
    email: "",
    nickname: "",
    link: "",
    career: "없음",
    education: "",
  },
  {
    id: "angel1234567",
    pageId: 16,
    password: "close122222@@",
    name: "윤미영",
    phoneNumber: "010-2323-2323",
    birthday: "2010-06-09",
    recruiter: false,
    email: "",
    nickname: "",
    link: "",
    career: "없음",
    education: "",
  },
];
