export const userInfo = [
  {
    id: "1",
    pageId: 1,
    password: "close22@@",
    name: "김예은",
    phoneNumber: "010-2222-2222",
    birthday: "1990-01-01",
    recruiter: true,
    email: "nabinabi1110@naver.com",
    nickname: "옝",
    link: "",
    career: "있음",
    education: "학사",
    contact: 0
  },
  {
    id: "2",
    pageId: 2,
    password: "close12@@",
    name: "김태연",
    phoneNumber: "010-1234-5678",
    birthday: "1990-01-01",
    recruiter: false,
    email: "tylove@naver.com",
    nickname: "탱구리",
    link: "",
    career: "없음",
    education: "학사",
    contact: 0
  },
  {
    id: "3",
    pageId: 3,
    password: "close12@@",
    name: "조수연",
    phoneNumber: "010-1234-5678",
    birthday: "1990-01-01",
    recruiter: false,
    email: "sylove@naver.com",
    nickname: "이쁜이",
    link: "",
    career: "없음",
    education: "석사",
    contact: 0
  },
  {
    id: "4",
    pageId: 4,
    password: "close12@@",
    name: "최현혜",
    phoneNumber: "010-1234-5678",
    birthday: "1990-01-01",
    recruiter: false,
    email: "hhlove@naver.com",
    nickname: "현혜씽",
    link: "",
    career: "있음",
    education: "박사",
    contact: 0
  },
  {
    id: "5",
    pageId: 5,
    password: "close12@@",
    name: "홍길동",
    phoneNumber: "010-1234-5678",
    birthday: "1990-01-01",
    recruiter: false,
    email: "example@example.com",
    nickname: "흰둥이",
    link: "",
    career: "있음",
    education: "석사",
    contact: 0
  },
  {
    id: "6",
    pageId: 6,
    password: "close12@@",
    name: "홍길동",
    phoneNumber: "010-1234-5678",
    birthday: "1990-01-01",
    recruiter: false,
    email: "example@example.com",
    nickname: "honghong",
    link: "",
    career: "없음",
    education: "박사",
    contact: 0
  },
  {
    id: "7",
    pageId: 7,
    password: "close12@@",
    name: "홍길동",
    phoneNumber: "010-1234-5678",
    birthday: "1990-01-01",
    recruiter: false,
    email: "example@example.com",
    nickname: "길동이",
    link: "",
    career: "있음",
    education: "석사",
    contact: 0
  },
];
